# Generated by Django 4.1.5 on 2023-01-30 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Имя задачи", max_length=300)),
                (
                    "is_done",
                    models.BooleanField(default=False, help_text="Выполнена ли задача"),
                ),
                (
                    "start_dt",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата и время создания"
                    ),
                ),
                (
                    "end_dt",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Дата и время завершения",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
